### ISSUE TITLE
Nodots = true 

### ISSUE THREAD

**Issue by MortenKJ** [mikeobrien/grunt-nunit-runner#10]
Hello. I have a question about the nodots option. If i set it to true, all the dots are printet on a new line in the console. Would it be possible to change this so that they print on the same line?

**Comment by meilke** [comment]
:+1:

**Comment by MortenKJ** [comment]
Is that a "yes, I will change that", og a "yes, it can be done" ?

**Comment by mikeobrien** [comment]
I don't think so but this would be a question for the nunit team. The grunt
runner simply calls nunit and passes the flags.

**Comment by MortenKJ** [comment]
Oh, okay then. I'll try and look into it. If I find a solution, I'll post it back here

**Comment by ricardovsilva** [comment]
My sugestion is to close this issue since this is not a grunt-nunit-runner issue.
