### ISSUE TITLE
NUnit V3 support

### ISSUE THREAD

**Issue by bbaia** [mikeobrien/grunt-nunit-runner#12]
Hi,

It seems the grunt task is not compatible with NUnit latest version 3.0.1.
Have you planned to support NUnit V3 ?
It would be great to have an option to switch between version V2/V3.

Regards,

**Comment by mikeobrien** [comment]
Naw, I don't use grunt anymore so not planning on upgrading it myself. But would welcome a PR if someone is interested in handling that.

**Comment by bbaia** [comment]
Thanks for the quick answer.
Lokks like it's time to move to gulp or directly to node/npm...

**Comment by mikeobrien** [comment]
Yeah, I ended up moving to gulp, really happy with it. There is a gulp plugin for NUnit that works great and supports 3.x: https://github.com/keithmorris/gulp-nunit-runner

**Comment by mikeobrien** [comment]
Fixed by @ricardovsilva and pushed to NPM.
